# Generated by Django 4.2.7 on 2023-11-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudianteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstudiante', models.CharField(blank=True, max_length=32, null=True)),
                ('apellidoEstudiante', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
