# Generated by Django 4.2.7 on 2023-11-29 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='almacenSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAlmacen', models.CharField(blank=True, max_length=32, null=True)),
                ('codigoAlmacen', models.CharField(blank=True, max_length=32, null=True)),
                ('direccionAlmacen', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuarioExtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoUsuario', models.CharField(blank=True, max_length=32, null=True)),
                ('rolUsuario', models.CharField(blank=True, max_length=32, null=True)),
                ('almacenUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app3.almacensistema')),
                ('usuarioAsociado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
