# Generated by Django 4.2.7 on 2023-12-06 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(blank=True, max_length=64, null=True)),
                ('codigoProducto', models.CharField(blank=True, max_length=32, null=True)),
                ('precioProducto', models.CharField(blank=True, max_length=16, null=True)),
                ('cantidadProducto', models.CharField(blank=True, max_length=16, null=True)),
                ('pesoProducto', models.CharField(blank=True, max_length=16, null=True)),
                ('almacenProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.almacensistema')),
            ],
        ),
    ]
