# Generated by Django 4.2.7 on 2023-12-08 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_productosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotizacionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(blank=True, max_length=64, null=True)),
                ('documentoCliente', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productoAsociadoCoti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProductoCoti', models.CharField(blank=True, max_length=16, null=True)),
                ('precioProductoCoti', models.CharField(blank=True, max_length=16, null=True)),
                ('cotizacionAsociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.cotizacionsistema')),
                ('productoAsociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app3.productosistema')),
            ],
        ),
    ]
